after_script:
  - rake travis:after -t
before_script:
  - gem install isolate hoe-travis --no-rdoc --no-ri
  - rake travis:before -t
language: ruby
script: rake travis
rvm:
  - 1.9.3
  - ruby-head
notifications:
  email: false
